### PR TITLE
Add colcon support for building ROS2 workspaces and add --build-tool argument

### PR DESCRIPTION
**Pull request by Rayman**
This PR adds a `--build-tool` argument to `ros-get ws-create`. By default it will try to automatically determine which build tool to use, but this can be manually be overrided. This will allow users to generate ROS2 workspace, but also to build ROS1 workspaces with colcon.

Fix https://github.com/Rayman/ros-get/issues/103

### CODE REVIEW

**Review by reinzor — CHANGES_REQUESTED** [review]
```
$ ros-get ws-create --colcon https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml /opt/ros/noetic/
/bin/sh: 1: colcon: not found
```

We should add the `colcon` dep.

**Comment by Rayman** [comment]
> We should add the `colcon` dep.

Hmm good point. But are we wasting space in the docker container if we have both catkin & colcon installed. What do you think about using `extras_require` for managing this? https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies

We could have:
```
pip install ros-get[colcon]
pip install ros-get[catkin_tools]
```

**Comment by reinzor** [comment]
🤔 I would just add the dependency, then it always works.

**Comment by reinzor** [comment]
Another thing we should think of is how a user "knows" whether it is a `colcon` workspace so that it can `source` the correct `setup.bash` in its `bash` setup files. For `catkin` it is `devel/setup.bash`, for `colcon` it is `install/setup.bash` if I am correct.

**Comment by Timple** [comment]
You might always first source install then devel. (if exists of course).

**Comment by Rayman** [comment]
I have a snippet for that, I'll update the `setup.bash` with that

**Comment by Rayman** [comment]
I'ved added `colcon-common-extensions' as dependency. Let's see if all my CI's still succeed

**Comment by Rayman** [comment]
> You might always first source install then devel. (if exists of course).

@Timple, see https://github.com/Rayman/ros-get/pull/102/files#diff-ab55cd33c997f1accf14a7afa9338e405fff5c46346b920a421dfbe1d1e0f21b

**Review by reinzor — APPROVED** [review]

**Comment by Timple** [comment]
Maybe colcon can be the default if a ROS2 installation is detected?

Going forward in future, this argument would always have to be passed...

**Comment by Rayman** [comment]
> Maybe colcon can be the default if a ROS2 installation is detected?
I'll try to do that in a follow up PR. I've looked at the files in `/opt/ros/foxy`, but I can't find any marker to indicate it was build with colcon. There is a marker file for `catkin`, but I'm not sure what the logic then would be.

**Comment by Rayman** [comment]
Hmm, maybe something like this:
```py
if args.colcon:
	make_ws_with_colcon():
else:
	if ws_is_catkin():
		make_ws_with_catkin_tools():	
	else:
		make_ws_with_colcon():
```

**Comment by reinzor** [comment]
🤔, sounds like weird behavior to me. Also if we add - -colcon that I.
Plies that it is disabled by default. Then I would change the arg for
something else like - - toolchain colcon/catkin and use other defaults
depending on some other vars.

**Comment by Timple** [comment]
Or sane defaults but you can override with `--colcon` and `--catkin`

**Comment by Rayman** [comment]
I've added a `--build-tool` argument (that's what they call it in ros-infrastructure). Without it, it tries to determine the type of workspace automatically.

**Pull request merged**
