### PR TITLE
fix(): update after some breaking changes in dependencies, fixes #111

### LINKED ISSUE #111: AttributeError: 'Namespace' object has no attribute 'buildlist'
Running `ros-get ws-create`:
```
Traceback (most recent call last):
  File "/home/rokus/.local/bin/ros-get", line 8, in <module>
    sys.exit(main())
  File "/home/rokus/.local/lib/python3.8/site-packages/ros_get/__main__.py", line 169, in main
    return func(**vars(args))
  File "/home/rokus/.local/lib/python3.8/site-packages/ros_get/workspace.py", line 64, in create
    result = create_workspace_with_catkin_tools(extend_path, dir)
  File "/home/rokus/.local/lib/python3.8/site-packages/ros_get/workspace.py", line 196, in create_workspace_with_catkin_tools
    if catkin_config.main(
  File "/usr/lib/python3/dist-packages/catkin_tools/verbs/catkin_config/cli.py", line 168, in main
    if opts.buildlist is not None:
AttributeError: 'Namespace' object has no attribute 'buildlist'
```

### PR DESCRIPTION
**Pull request by rokusottervanger**

### CODE REVIEW

**Review by Rayman — APPROVED** [review]

**Comment by rokusottervanger** [comment]
I don't think we're getting a response from Travis

**Comment by Rayman** [comment]
We should have switched to github actions: https://github.com/Rayman/ros-get/commit/69b151494c0222ac299824ebe532c35f0b889cc9

**Comment by rokusottervanger** [comment]
Friendly ping

**Comment by Rayman** [comment]
Merged in 1e7a8cd7579f8a6869c93f945b7d43dc9e08ffd7 (I had to rebase)

**Pull request closed without merging**
