### PR TITLE
Call rosdep update on ws-create

### PR DESCRIPTION
**Pull request by reinzor**
Fixes https://github.com/Rayman/ros-get/issues/59

### CODE REVIEW

**Comment by reinzor** [comment]
ping

**Comment by Rayman** [comment]
If you create a new workspace, the environment variables of them will not have loaded. Does this rosdep update then work?

**Comment by reinzor** [comment]
Yes, seems to work.

-Rein

**Comment by Rayman** [comment]
I tried this in a fresh docker install, but I think that the `rosdep update` will not be called with the `ROS_HOME` variable of the new workspace, so it will use just the global `~/.ros/rosdep` folder`. 

The easiest options is to source the new workspace again and then `rosdep update`, but how can we automate that?

See below a log file of the result.
```
root@748dff50da26:~/ros# ros-get ws-create distro.yaml /opt/ros/kinetic/
...  (lots of lines)                                                                                
[build] Runtime: 1.5 seconds total.                                                                               
[INFO] root: symlink '/root/ros' => '/root/.config/ros-get/workspaces/ros'
[INFO] ros_get.workspace: saved the workspace as 'ros'
[INFO] ros_get.workspace: created first workspace, let's make it the default
[INFO] root: symlink 'workspaces/ros' => '/root/.config/ros-get/workspace'
reading in sources list data from /etc/ros/rosdep/sources.list.d
Warning: running 'rosdep update' as root is not recommended.
  You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit file:///etc/ros/rosdep/base.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
Add distro "groovy"
Add distro "hydro"
Add distro "indigo"
Add distro "jade"
Add distro "kinetic"
Add distro "lunar"
Add distro "melodic"
updated cache in /root/.ros/rosdep/sources.cache
```
Now let's source the new workspace and try again:
```
root@748dff50da26:~/ros# source ~/.bashrc 
root@748dff50da26:~/ros# rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Warning: running 'rosdep update' as root is not recommended.
  You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit file:///etc/ros/rosdep/base.yaml
Query rosdistro index file:///root/.ruvu/rosdistro/project-exr1.yaml
Add distro "kinetic"
updated cache in /root/ros/home/rosdep/sources.cache
```
You can see the last line `updated cache in /root/ros/home/rosdep/sources.cache` that is different.

**Pull request closed without merging**
